//! Where the fixtures and the certificate are, for every module that needs one.
//!
//! Note:
//! - Constants, the way the HttpArena entries name /data and /etc/zix-tls. The
//!   entry names the path and the harness guarantees it: there a Dockerfile and
//!   a compose mount put the files in place, here localbench-build.sh and
//!   localbench-run.sh do, and both run from the repository root.

/// Fixture root: dataset.json and static/ live under it.
pub const DATA_DIR: []const u8 = "localbench/data";

/// The 50-item benchmark dataset.
pub const DATASET: []const u8 = "localbench/data/dataset.json";

/// Certificate pair for the TLS listener, generated by localbench-build.sh.
pub const TLS_CERT: []const u8 = "localbench/certs/server.crt";
pub const TLS_KEY: []const u8 = "localbench/certs/server.key";
