//! UDP PoC Client — rnd only, not part of src/
//! Zig 0.16.x
//!
//! Usage: zig run rnd/udp_client.zig -- [--bind-port <port>] [--server-port <port>]
//!        --bind-port    local bind port (default: 9101)
//!        --server-port  server port to connect to (default: 9100)
//!
//! NOTE: concurrency model uses process.Init / io.concurrent()
//!       should be configurable later (e.g. std.Thread.spawn for constrained envs)
//!
//! NOTE: endianness is native-endian; must match server
//!
//! NOTE: send_every is in milliseconds
//!       can be changed to nanoseconds later for sub-ms precision (trivial: change unit + field name)
//!       nanosecond granularity is not needed for UDP telemetry PoC
//!
//! NOTE: feedback reception — client reads ACK (0x06), NACK (0x15), or broadcast (TestPacket)
//!       from server; runs as a persistent io.concurrent() task
//!       the id field in received broadcasts is stamped by the server with the sender's
//!       connection index — the client does not need to set a meaningful id

const std = @import("std");

// --------------------------------------------------------- //

// NOTE: native-endian layout; must match server definition exactly
// NOTE: 'packet_type' maps to `int type` in spec — 'type' is a Zig keyword
const TestPacket = extern struct {
    id: [16]u8,
    packet_type: i32,
    register: u32,
    position: [3]f64,
};

// --------------------------------------------------------- //

const ClientConfig = struct {
    server_ip: []const u8 = "127.0.0.1",
    server_port: u16 = 9100,
    // explicit bind so server can send broadcast (and echo/ACK) back to a known port
    bind_port: u16 = 9101,
    // if true: send one packet and exit; receive task is still spawned but response may not
    // arrive before the process exits — acceptable for one-shot fire-and-forget use
    send_once: bool = false,
    // NOTE: milliseconds; change to nanoseconds later if sub-ms precision is needed
    send_every: u64 = 1000,
};

// --------------------------------------------------------- //

// NOTE: receive loop runs as a persistent concurrent task; occupies one thread pool slot.
//       In src/: decode into a typed result struct, not raw-byte interpretation by length.
const ReceiveTask = struct {
    socket: std.Io.net.Socket,
    io: std.Io,
};

fn receiveFeedback(task: ReceiveTask) void {
    var buf: [@sizeOf(TestPacket)]u8 = undefined;
    while (true) {
        const msg = task.socket.receive(task.io, &buf) catch |err| {
            std.debug.print("recv error: {}\n", .{err});
            continue;
        };
        if (msg.data.len == 1) {
            const byte = msg.data[0];
            if (byte == 0x06) {
                std.debug.print("recv | ACK\n", .{});
            } else if (byte == 0x15) {
                std.debug.print("recv | NACK\n", .{});
            } else {
                std.debug.print("recv | unknown byte: 0x{x:0>2}\n", .{byte});
            }
        } else if (msg.data.len == @sizeOf(TestPacket)) {
            const pkt: TestPacket = @bitCast(buf);
            const id_end = std.mem.indexOfScalar(u8, &pkt.id, 0) orelse pkt.id.len;
            std.debug.print(
                "recv | from={s} x={d:.4} y={d:.4} z={d:.4}\n",
                .{ pkt.id[0..id_end], pkt.position[0], pkt.position[1], pkt.position[2] },
            );
        } else {
            std.debug.print("recv | unexpected {d} bytes\n", .{msg.data.len});
        }
    }
}

// --------------------------------------------------------- //

// NOTE: id field is left zeroed — the server stamps the sender's connection index
//       into the id field before broadcasting, so the client's own id is irrelevant for peers
// position: x, y, z movement values in [-1.0, 1.0), generated by caller's PRNG
fn makeTestPacket(position: [3]f64) TestPacket {
    return TestPacket{
        .id = [_]u8{0} ** 16,
        .packet_type = 1,
        .register = 42,
        .position = position,
    };
}

fn sendPacket(socket: std.Io.net.Socket, io: std.Io, dest: std.Io.net.IpAddress, position: [3]f64) void {
    const pkt = makeTestPacket(position);
    socket.send(io, &dest, std.mem.asBytes(&pkt)) catch |err| {
        std.debug.print("send error: {}\n", .{err});
        return;
    };
    std.debug.print(
        "sent | packet_type={d} register={d} x={d:.4} y={d:.4} z={d:.4}\n",
        .{ pkt.packet_type, pkt.register, pkt.position[0], pkt.position[1], pkt.position[2] },
    );
}

// --------------------------------------------------------- //

pub fn main(process: std.process.Init) !void {
    const io = process.io;
    var config: ClientConfig = .{};

    var args_it = std.process.Args.Iterator.init(process.minimal.args);
    _ = args_it.skip(); // skip argv[0]
    while (args_it.next()) |arg| {
        if (std.mem.eql(u8, arg, "--bind-port")) {
            if (args_it.next()) |val| {
                config.bind_port = std.fmt.parseInt(u16, val, 10) catch config.bind_port;
            }
        } else if (std.mem.eql(u8, arg, "--server-port")) {
            if (args_it.next()) |val| {
                config.server_port = std.fmt.parseInt(u16, val, 10) catch config.server_port;
            }
        }
    }

    const bind_addr = try std.Io.net.IpAddress.parse("0.0.0.0", config.bind_port);
    const socket = try bind_addr.bind(io, .{ .mode = .dgram, .protocol = .udp });
    defer socket.close(io);

    const dest = try std.Io.net.IpAddress.parse(config.server_ip, config.server_port);

    std.debug.print("zix udp client: bound 0.0.0.0:{d} -> {s}:{d}\n", .{ config.bind_port, config.server_ip, config.server_port });

    // persistent receive task — reads server feedback for client lifetime
    _ = io.concurrent(receiveFeedback, .{ReceiveTask{ .socket = socket, .io = io }}) catch |err| {
        std.debug.print("recv task spawn error: {}\n", .{err});
    };

    // PRNG seeded from clock; access is sequential (sleep between sends prevents concurrent use)
    const prng_ts = std.Io.Clock.Timestamp.now(io, .awake);
    const prng_seed: u64 = @truncate(@as(u128, @bitCast(@as(i128, prng_ts.raw.nanoseconds))));
    var prng = std.Random.DefaultPrng.init(prng_seed);
    const rng = prng.random();

    if (config.send_once) {
        const pos = [3]f64{
            rng.float(f64) * 2.0 - 1.0,
            rng.float(f64) * 2.0 - 1.0,
            rng.float(f64) * 2.0 - 1.0,
        };
        sendPacket(socket, io, dest, pos);
        return;
    }

    while (true) {
        const pos = [3]f64{
            rng.float(f64) * 2.0 - 1.0,
            rng.float(f64) * 2.0 - 1.0,
            rng.float(f64) * 2.0 - 1.0,
        };
        _ = io.concurrent(sendPacket, .{ socket, io, dest, pos }) catch |err| {
            std.debug.print("concurrent error: {}\n", .{err});
            sendPacket(socket, io, dest, pos); // fallback: inline
        };
        try std.Io.sleep(io, std.Io.Duration.fromMilliseconds(@as(i64, @intCast(config.send_every))), .awake);
    }
}
